-- =====================================================================
-- FarmTech Solutions - Fase 4 CAP 1
-- Schema relacional para Oracle Database (FIAP) - ENTREGA OBRIGATORIA
-- Equivalente Oracle do src/sql/01_schema.sql (SQLite).
-- =====================================================================
-- Tabelas:
--   culturas         -> catalogo de culturas monitoradas
--   leituras_sensor  -> telemetria dos sensores + variaveis agronomicas + alvo
--   acoes_irrigacao  -> recomendacoes de manejo geradas pelo modelo de ML
--
-- Como executar (SQL Developer conectado ao Oracle FIAP):
--   Abrir este arquivo e rodar como script (F5).
-- =====================================================================

-- ---------------------------------------------------------------------
-- DROP idempotente: Oracle nao tem "DROP TABLE IF EXISTS".
-- O bloco ignora ORA-00942 (tabela inexistente) na 1a execucao.
-- ---------------------------------------------------------------------
BEGIN
    FOR t IN (SELECT table_name FROM user_tables
              WHERE table_name IN ('ACOES_IRRIGACAO', 'LEITURAS_SENSOR', 'CULTURAS'))
    LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

-- ---------------------------------------------------------------------
-- culturas: uma linha por cultura agricola monitorada
-- ---------------------------------------------------------------------
CREATE TABLE culturas (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR2(60)  NOT NULL UNIQUE,
    area_hectare  NUMBER(10,2)  NOT NULL,
    data_plantio  DATE          NOT NULL,
    CONSTRAINT ck_culturas_area CHECK (area_hectare > 0)
);

-- ---------------------------------------------------------------------
-- leituras_sensor: telemetria coletada no campo (tabela-fato do ML).
-- Estende o schema base (umidade, ph, temperatura, luminosidade) com as
-- variaveis agronomicas reusadas da Fase 3 (N, P, K, chuva) e o alvo de
-- regressao da Fase 4 (produtividade_kg_ha).
-- ---------------------------------------------------------------------
CREATE TABLE leituras_sensor (
    id                   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts                   TIMESTAMP     NOT NULL,            -- momento da leitura
    sensor_id            VARCHAR2(10)  NOT NULL,            -- ex.: S001..S010
    cultura_id           NUMBER        NOT NULL,
    temperatura          NUMBER(6,2),
    umidade              NUMBER(6,2),
    ph                   NUMBER(4,2),
    luminosity           NUMBER(10,2),
    n                    NUMBER(8,2),                       -- Nitrogenio (kg/ha)
    p                    NUMBER(8,2),                       -- Fosforo (kg/ha)
    k                    NUMBER(8,2),                       -- Potassio (kg/ha)
    chuva_mm             NUMBER(8,2),                       -- Precipitacao (mm)
    produtividade_kg_ha  NUMBER(10,2),                      -- Alvo (kg/ha)
    CONSTRAINT ck_ls_temp  CHECK (temperatura BETWEEN -10 AND 60),
    CONSTRAINT ck_ls_umid  CHECK (umidade BETWEEN 0 AND 100),
    CONSTRAINT ck_ls_ph    CHECK (ph BETWEEN 0 AND 14),
    CONSTRAINT ck_ls_lum   CHECK (luminosity BETWEEN 0 AND 100000),
    CONSTRAINT fk_ls_cultura FOREIGN KEY (cultura_id) REFERENCES culturas (id)
);

-- ---------------------------------------------------------------------
-- acoes_irrigacao: recomendacoes de manejo geradas a partir das predicoes
-- ---------------------------------------------------------------------
CREATE TABLE acoes_irrigacao (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cultura_id        NUMBER        NOT NULL,
    data_acao         DATE          NOT NULL,
    volume_m3         NUMBER(10,2),
    recomendacao_ml   VARCHAR2(500),
    CONSTRAINT ck_ai_volume CHECK (volume_m3 >= 0),
    CONSTRAINT fk_ai_cultura FOREIGN KEY (cultura_id) REFERENCES culturas (id)
);

-- ---------------------------------------------------------------------
-- Indices em colunas frequentemente consultadas
-- ---------------------------------------------------------------------
CREATE INDEX idx_leituras_sensor_id ON leituras_sensor (sensor_id);
CREATE INDEX idx_leituras_ts        ON leituras_sensor (ts);
CREATE INDEX idx_leituras_cultura   ON leituras_sensor (cultura_id);
CREATE INDEX idx_acoes_cultura      ON acoes_irrigacao (cultura_id);
